apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f airbyte-docker-compose.yml
    kompose.version: 1.26.1 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f airbyte-docker-compose.yml
        kompose.version: 1.26.1 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
        - env:
            - name: AIRBYTE_ROLE
            - name: AIRBYTE_VERSION
              value: 0.38.4-alpha
            - name: CONFIG_DATABASE_PASSWORD
            - name: CONFIG_DATABASE_URL
            - name: CONFIG_DATABASE_USER
            - name: CONFIG_ROOT
              value: /data
            - name: DATABASE_PASSWORD
              value: docker
            - name: DATABASE_URL
              value: jdbc:postgresql://db:5432/airbyte
            - name: DATABASE_USER
              value: docker
            - name: INTERNAL_API_HOST
              value: airbyte-server:8001
            - name: JOB_MAIN_CONTAINER_CPU_LIMIT
            - name: JOB_MAIN_CONTAINER_CPU_REQUEST
            - name: JOB_MAIN_CONTAINER_MEMORY_LIMIT
            - name: JOB_MAIN_CONTAINER_MEMORY_REQUEST
            - name: LOCAL_DOCKER_MOUNT
              value: /tmp/airbyte_local
            - name: LOCAL_ROOT
              value: /tmp/airbyte_local
            - name: LOG_LEVEL
              value: INFO
            - name: NEW_SCHEDULER
            - name: SECRET_PERSISTENCE
            - name: SUBMITTER_NUM_THREADS
              value: "10"
            - name: SYNC_JOB_MAX_ATTEMPTS
              value: "3"
            - name: SYNC_JOB_MAX_TIMEOUT_DAYS
              value: "3"
            - name: TEMPORAL_HOST
              value: airbyte-temporal:7233
            - name: TRACKING_STRATEGY
              value: segment
            - name: WEBAPP_URL
              value: http://localhost:8000/
            - name: WORKER_ENVIRONMENT
            - name: WORKSPACE_DOCKER_MOUNT
              value: airbyte_workspace
            - name: WORKSPACE_ROOT
              value: /tmp/workspace
          image: airbyte/scheduler:0.38.4-alpha
          name: airbyte-scheduler
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /tmp/workspace
              name: workspace
            - mountPath: /tmp/airbyte_local
              name: scheduler-claim2
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
        - name: scheduler-claim2
          persistentVolumeClaim:
            claimName: scheduler-claim2
status: {}
